name: Release jar
on:
  push:
    tags: ['v*.*.*']
  workflow_dispatch: {}
permissions:
  contents: read
jobs:
  release:
    permissions:
      contents: write
      id-token: write
      attestations: write
    uses: Query-farm/vgi-actions/.github/workflows/java-release.yml@v1
    secrets: inherit
    with:
      jar: build/libs/*-all.jar
      build_cmd: "./gradlew shadowJar"
